version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    build: ./sql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$MYSQL_DB
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $APP_PORT:$APP_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$MYSQL_DB
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes: 
  db: